### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by deleyva** [catedu/moodle-docker-production#10]
I've tested it locally and every page loads very slowly.

```
  Nombre del modelo:	MacBook Pro
  Identificador del modelo:	MacBookPro12,1
  Nombre del procesador:	Intel Core i5
  Velocidad del procesador:	2,7 GHz
  Cantidad de procesadores:	1
  Cantidad total de núcleos:	2
  Caché de nivel 2 (por núcleo):	256 KB
  Caché de nivel 3:	3 MB
  Memoria:	8 GB

Docker version 19.03.8, build afacb8b
```

**Comment by juanda99** [comment]
It's a mac issue, I'm suffering it too!
https://docs.docker.com/docker-for-mac/osxfs-caching/
I've changed volumes to delegated but it isn't fast anyway and I don't know if it would affect to linux environment.

**Comment by deleyva** [comment]
Ok! I hope it works better on linux. It seems it does so far in the staging server you set up.

**Comment by juanda99** [comment]
I close it as we will work most of the time with linux.
