### ISSUE TITLE
Import theme not working inside container

### ISSUE THREAD

**Issue by deleyva** [catedu/moodle-docker-production#12]
Trying to understand how theme settings import works i've logged in the container and run:

```
moosh -n theme-settings-import --targettheme snap snap_settings_1558197087.tar.gz
```

It adds the image and we can see them in the admin panel in the Moodle frontend but, as it adds below the preexisting one, it doesn't make any change. After erasing the first image, it works.

![Captura de pantalla 2020-05-24 a las 15 22 08](https://user-images.githubusercontent.com/10669244/82755566-a714b080-9dd4-11ea-972b-241c6752c890.png)

It doesn't even add poster image nor poster image name in the database.

**Comment by juanda99** [comment]
I checked and it's almost ok:
tmuras/moosh#318

**Comment by juanda99** [comment]
I close it as we move to another theme.
