### ISSUE TITLE
Get it ready for Moodle 3.7

### ISSUE THREAD

**Issue by juanda99** [catedu/moodle-docker-production#4]
theme plugin theme_snap is not ready for 3.8.
We should add another dir with the same configuration for 3.7.

**Comment by lmorillas** [comment]
> We should add another dir with the same configuration for 3.7.

Sure? 

> Bug fixes for security issues in 3.7.x will end 9 November 2020

**Comment by juanda99** [comment]
It's supposed to be fix by summer: blackboard-open-source/moodle-theme_snap#163
Preparing 3.7 could be fast.
Meanwhile we need something to show or to use just in case of delay. Is it this way @deleyva?

**Comment by deleyva** [comment]
It is as you say @juanda99

**Comment by juanda99** [comment]
Ready! Default image in docker-compose changed to 3.7
